added error handling

diff --git a/bin/markdown2shower b/bin/markdown2shower
--- a/bin/markdown2shower
+++ b/bin/markdown2shower
@@ -9,6 +9,11 @@ template=${3:-"template.html"}
 
 tmpfile="tmp$$tmp"
 
+if [ ! -f "$template" ]; then
+	echo "ERROR: template file (\`$template\`) could not be found"
+	exit 1
+fi
+
 # post-process regular Markdown output to account for common mismatches
 ~/Scripts/Markdown.pl | \
 		sed -e "s#\(<pre>\)<code>#\1#g" -e "s#</code>\(</pre>\)#\1#g" \
